### ISSUE TITLE
Safe to use beta sdk in production env?

### ISSUE THREAD

**Issue by valeedyounas** [checkout/checkout-sdk-go#7]
Hello team!

Good work on the SDK for golang. I see the status is beta for now. Can you guys confirm if it is safe to use in a production environment? If not, when can we expect a stable release of the golang sdk for checkout.

Thank you for your contributions

**Comment by rsaestrela** [comment]
Hi @valeedyounas. I was not involved in the development of this particular codebase since the beginning, but looking to the code I would say that's safe to use in production. As this is an (old) project and it is not actively maintained, the only concern is the clear lack of compatibility and features to mirror the current Checkout API state (endpoints, schema, auth). I've [commited](https://github.com/checkout/checkout-sdk-go/commit/7718900ce6015790bf622e5d8b9fce5324e9dc18) recently some changes to make it usable with [Four](https://www.checkout.com/docs/four/) static keys, for example - but this doesn't make it automatically compliant with the [Four schema](https://api-reference.checkout.com/preview/crusoe/). If you're using Default keys (sk/pk_UUID format) it should be ok, otherwise it's not really recommended to use it (it will work, but some stuff might not work as expected). I recommend you to test your implementation in sandbox first.

The good news is that we're actively working on building the next generation of SDK's, fully compatible with Default/Four schemas and different auth mechanisms. There have been new fully compliant releases weekly on the Java, NET, PHP & Python SDKs but not on this one because we just started working on the new codebase. We plan to make it public and to release the next v2 (most probably v1.0.0beta1) in 2 months approx. and that one we can guarantee you will be stable enough to use in production.

**Comment by valeedyounas** [comment]
Hello @rsaestrela. Thank you for the update. Closing comment.
